apiVersion: v1
kind: Template
metadata:
  name: app-springboot-deploy
  annotations:
    description: >-
      A simple deployment config to deploy apps.
    iconClass: icon-jboss
    tags: 'java,springboot,dev'
    version: '2.0'
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APP_NAME}${APP_MAJOR_VERSION}
      annotations:
        prometheus.io/path: /prometheus
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
      labels:
        component: ${APP_NAME}
        group: dev
        project: ${APP_NAME}
        provider: s2i
        version: ${APP_MAJOR_VERSION}
        appname: ${APP_NAME}
        appversion: ${APP_VERSION}
        buildnumber: ${JENKINS_BUILD_NUMBER}
        gitcommitid: ${GIT_COMMIT_ID}
    spec:
      ports:
        - name: '${APP_NAME}${APP_MAJOR_VERSION}-http'
          port: 8080
          targetPort: 8080
        - name: '${APP_NAME}${APP_MAJOR_VERSION}-prometheus-http'
          port: 9090
          targetPort: 9090
      selector:
        component: '${APP_NAME}'
        deploymentconfig: '${APP_NAME}${APP_MAJOR_VERSION}'
        group: dev
        project: '${APP_NAME}'
        provider: s2i
        version: '${APP_MAJOR_VERSION}'
      type: ClusterIP
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        component: '${APP_NAME}'
        group: dev
        project: '${APP_NAME}'
        provider: s2i
        version: '${APP_MAJOR_VERSION}'
        appname: ${APP_NAME}
        appversion: ${APP_VERSION}
        buildnumber: ${JENKINS_BUILD_NUMBER}
        gitcommitid: ${GIT_COMMIT_ID}
      name: '${APP_NAME}${APP_MAJOR_VERSION}'
    spec:
      replicas: ${NUMBER_OF_REPLICAS}
      selector:
        component: '${APP_NAME}'
        deploymentconfig: '${APP_NAME}${APP_MAJOR_VERSION}'
        group: dev
        project: '${APP_NAME}'
        provider: s2i
        version: '${APP_MAJOR_VERSION}'
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources: {}
      template:
        metadata:
          labels:
            component: '${APP_NAME}'
            deploymentconfig: '${APP_NAME}${APP_MAJOR_VERSION}'
            group: dev
            project: '${APP_NAME}'
            provider: s2i
            version: '${APP_MAJOR_VERSION}'
            appname: ${APP_NAME}
            appversion: ${APP_VERSION}
            buildnumber: ${JENKINS_BUILD_NUMBER}
            gitcommitid: ${GIT_COMMIT_ID}
          annotations:
            bfs.integration.sapm.acl.allowedKeys: '${APP_NAME}${APP_MAJOR_VERSION}'
        spec:
          volumes:
            - name: config
              configMap:
                name: '${APP_NAME}${APP_MAJOR_VERSION}'
                defaultMode: 420
          containers:
            - name: '${APP_NAME}${APP_MAJOR_VERSION}'
              image: '${APP_NAME}${APP_MAJOR_VERSION}:${IMAGE_TAG}'
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom: {fieldRef: {fieldPath: metadata.namespace}}
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: TZ
                  value: Australia/Sydney
                - name: SPRING_CONFIG_LOCATION
                  value: /etc/config/
                - name: AB_OFF
                  value: 'true'
                - name: AB_JOLOKIA_OFF
                  value: 'true'
                - name: AB_JMX_EXPORTER_OFF
                  value: 'true'
                - name: JAVA_MAX_MEM_RATIO
                  value: '75'
                - name: JAVA_OPTIONS
                  value: '-javaagent:/opt/appdynamics/javaagent.jar -Djava.security.egd=file:/dev/./urandom -XX:+PrintFlagsFinal -XX:+PrintGCDetails -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap'
              livenessProbe:
                httpGet:
                  path: /health
                  port: 9090
                  scheme: HTTP
                initialDelaySeconds: 100
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 15
              readinessProbe:
                httpGet:
                  path: /health
                  port: 9090
                  scheme: HTTP
                initialDelaySeconds: 100
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 15
              resources:
                limits:
                  cpu: '${CPU_LIMIT}'
                  memory: '${MEM_LIMIT}'
                requests:
                  cpu: '${CPU_REQUEST}'
                  memory: '${MEM_REQUEST}'
              volumeMounts:
                - name: config
                  readOnly: true
                  mountPath: /etc/config
    status: {}
parameters:
  - name: APP_NAME
    displayName: Application Name
    description: The name assigned to the application.
    required: true
  - name: BUILDER_VERSION
    displayName: Builder version
    description: The version of the FIS S2I builder image to use.
    value: '2.0'
  - name: APP_MAJOR_VERSION
    displayName: Application Major Version
    description: The application major version from the pom version tag e.g. 1 for 1.0.0-SNAPSHOT.
  - name: CPU_REQUEST
    displayName: CPU request
    description: The amount of CPU to requests.
    value: 400m
    required: true
  - name: CPU_LIMIT
    displayName: CPU limit
    description: The amount of CPU the container is limited to use.
    value: 600m
    required: true
  - name: MEM_REQUEST
    displayName: CPU request
    description: The amount of CPU to requests.
    value: 768Mi
    required: true
  - name: MEM_LIMIT
    displayName: CPU limit
    description: The amount of CPU the container is limited to use.
    value: 1024Mi
    required: true
  - name: NAMESPACE
    displayName: k8s namespace
    description: K8s namesapce
    value: dev
    required: true
  - name: GIT_COMMIT_ID
    displayName: GIT Commit ID
    description: GIT Commit ID from Jenkins
    required: true
  - name: JENKINS_BUILD_NUMBER
    displayName: Jenkins Build Number
    description: Jenkins Build Number
    required: true
  - name: APP_VERSION
    displayName: RAW app version
    description: RAW app version e.g. 1.0
    required: true
  - name: NUMBER_OF_REPLICAS
    displayName: How many pods
    description: How many pods
    required: true
  - name: IMAGE_TAG
    displayName: raw app version for dev env, uat for uat and prod for prod
    description: raw app version for dev env, uat for uat and prod for prod
    required: true
  - name: EXTERNAL_NAMESPACE
    displayName: External namespace
    description: External namespace
    required: true

labels:
  template: app-springboot-deploy
